### ISSUE TITLE
FPS meter visibility

### ISSUE THREAD

**Issue by Atknssl** [sriharsha2000/Slide#7]
Player doesn't need to see FPS meter all the time, maybe a setting for visibility of FPS meter can be added and it can be changed from pause menu.

**Comment by srihk** [comment]
Added a toggle for FPS Counter in the pause menu: [4ba28f837c543f3239bafbaf4dd1cf3b4155cfb9](https://github.com/sriharsha2000/RoughDrift/commit/4ba28f837c543f3239bafbaf4dd1cf3b4155cfb9)
